/**
 * An OIDC provider adapter over `openid-client`.
 *
 * ONE adapter serves every OIDC provider — Google, Microsoft, Apple, Okta, any corporate
 * issuer — because they all implement the same specification. Adding a provider is a
 * configuration entry, not code, which is the property 06 §2 asks for and the reason the
 * identity module never names a provider.
 *
 * WHY A LIBRARY HERE AND NOT FOR TOTP. ADR-0017 draws the line at "can we verify it against
 * the standard itself". TOTP is one HMAC with published RFC vectors, so it is hand-written
 * and checked against them. OIDC is discovery, PKCE, nonce binding, ID-token signature
 * verification and JWKS rotation, with no conformance vectors we can run in CI and a long
 * history of implementation-level breaks. That one is delegated.
 */
import {
  allowInsecureRequests,
  authorizationCodeGrant,
  buildAuthorizationUrl,
  type Configuration,
  calculatePKCECodeChallenge,
  discovery,
  randomNonce,
  randomPKCECodeVerifier,
  randomState,
} from 'openid-client';
import type {
  OAuthProvider,
  ProviderId,
  StartedAuthorization,
  VerifiedProviderIdentity,
} from '../application/oauth-port.js';

export interface OidcProviderConfig {
  readonly id: ProviderId;
  readonly displayName: string;
  /** The issuer URL. Discovery reads its metadata; nothing about it is hard-coded. */
  readonly issuer: string;
  readonly clientId: string;
  readonly clientSecret: string;
  readonly allowedRedirectUris: readonly string[];
  readonly scope?: string | undefined;
  /**
   * Permits plain HTTP to the issuer.
   *
   * ONLY for a local test issuer. Production issuers are HTTPS and the library refuses
   * otherwise — which is the correct default, because an ID token fetched over HTTP has no
   * integrity guarantee at all. A test asserts this is never true for a configured provider.
   */
  readonly allowInsecureIssuer?: boolean | undefined;
}

/**
 * The claims we read. Everything else the provider returns is ignored — a claim we do not
 * read cannot influence a decision.
 */
interface OidcClaims {
  readonly sub: string;
  readonly email?: unknown;
  readonly email_verified?: unknown;
  readonly name?: unknown;
}

function readString(value: unknown): string | undefined {
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}

/**
 * Reads the provider's email-verified claim.
 *
 * STRICT, deliberately. Only a real boolean `true` or the exact string `"true"` counts —
 * some issuers serialise booleans as strings. Anything else, including absent, is false.
 *
 * The permissive reading (truthy) would treat the string `"false"` as verified, because a
 * non-empty string is truthy in JavaScript. That single coercion is enough to turn an
 * unverified provider address into an account.
 */
function readEmailVerified(value: unknown): boolean {
  if (value === true) return true;
  if (value === 'true') return true;
  return false;
}

export async function createOidcProvider(config: OidcProviderConfig): Promise<OAuthProvider> {
  const options = config.allowInsecureIssuer === true ? { execute: [allowInsecureRequests] } : {};
  const client: Configuration = await discovery(
    new URL(config.issuer),
    config.clientId,
    config.clientSecret,
    undefined,
    options,
  );
  if (config.allowInsecureIssuer === true) allowInsecureRequests(client);

  const scope = config.scope ?? 'openid email profile';

  return {
    id: config.id,
    displayName: config.displayName,
    allowedRedirectUris: config.allowedRedirectUris,

    async startAuthorization(redirectUri: string): Promise<StartedAuthorization> {
      // Generated by the library: CSPRNG entropy and the S256 challenge derivation, both of
      // which are easy to get subtly wrong by hand.
      const state = randomState();
      const nonce = randomNonce();
      const codeVerifier = randomPKCECodeVerifier();
      const codeChallenge = await calculatePKCECodeChallenge(codeVerifier);

      const url = buildAuthorizationUrl(client, {
        redirect_uri: redirectUri,
        scope,
        state,
        nonce,
        code_challenge: codeChallenge,
        // S256, never `plain`. The plain method sends the verifier itself, which defeats the
        // entire mechanism against an attacker who can read the authorization request.
        code_challenge_method: 'S256',
      });
      return { url: url.href, state, codeVerifier, nonce };
    },

    async exchangeCallback(params): Promise<VerifiedProviderIdentity> {
      // The library verifies state, exchanges the code with the PKCE verifier, validates the
      // ID token's signature against the issuer's JWKS, and checks iss, aud, exp and nonce.
      // Any failure throws, and the caller collapses every throw to one opaque outcome.
      const tokens = await authorizationCodeGrant(client, new URL(params.callbackUrl), {
        pkceCodeVerifier: params.codeVerifier,
        expectedState: params.expectedState,
        expectedNonce: params.expectedNonce,
        idTokenExpected: true,
      });

      const claims = tokens.claims() as OidcClaims | undefined;
      if (claims === undefined || readString(claims.sub) === undefined) {
        throw new Error('The provider returned no subject claim.');
      }

      // The access and refresh tokens in `tokens` are deliberately dropped here. Login is
      // federation, not an integration: we never call the provider again on this user's
      // behalf, so there is nothing to refresh and nothing worth storing. See migration 0009.
      return {
        provider: config.id,
        providerUserId: claims.sub,
        email: readString(claims.email),
        emailVerified: readEmailVerified(claims.email_verified),
        name: readString(claims.name),
      };
    },
  };
}
